# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-production
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-production
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - zeinfahrozi.my.id
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qwj9jj75armxlhtv3mkh7h9fytldwu7ylkpy9ns807fxrr7e0fkq329d6e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ2RFczg3WVhUQVlZK0Rp
        RWpESkM1RDRLU3hXQTFRUWxjc3RRNW9OM1dZCko3Y3pjZXBwZ3hwTVdUdStkV3Zp
        bEJSYmFtMGNJOFlzc3dGOGNjSkF6QW8KLS0tIFErUS9rTjFtTy9Zd1UzRExlY0N4
        MzNTT0RRZVZWeDBINTNMZm56cjJjVGsK/riC1yHa8f//e2p6BR8hkP0mQEsG29FM
        wmLbKrc0h9XPNytAuboDD+ttRYiO4rx1wmrnNSlqxFiuxB3IiWAx3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T21:07:11Z"
  mac: ENC[AES256_GCM,data:0Ts+T0LVOcT3Z6+lKyuUEtKFMxzuQoCuI/1VRWcizbIU8EHrPQDQl/CHq30C9EQohDtTOM074AS/U4T5hJ9w9bmjc71mPly4OY+Q7lrUbzMpgtarkHxi+1roEebohXfSxAKAkB9nw6y+4KaFVPwMPiABcI9OCvMXG6PV3uW4uts=,iv:zxnZbBj4t2P5xOxYPp0FFKOeXAht7FCb988AFI9fTfg=,tag:y/qwAci4vFTAxnHVUgEuNA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
---
# yaml-language-server: $schema=https://raw.githubusercontent.com/datreeio/CRDs-catalog/main/cert-manager.io/clusterissuer_v1.json
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
      - dns01:
          cloudflare:
            apiTokenSecretRef:
              name: cert-manager-secret
              key: api-token
        selector:
          dnsZones:
            - zeinfahrozi.my.id
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qwj9jj75armxlhtv3mkh7h9fytldwu7ylkpy9ns807fxrr7e0fkq329d6e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ2RFczg3WVhUQVlZK0Rp
        RWpESkM1RDRLU3hXQTFRUWxjc3RRNW9OM1dZCko3Y3pjZXBwZ3hwTVdUdStkV3Zp
        bEJSYmFtMGNJOFlzc3dGOGNjSkF6QW8KLS0tIFErUS9rTjFtTy9Zd1UzRExlY0N4
        MzNTT0RRZVZWeDBINTNMZm56cjJjVGsK/riC1yHa8f//e2p6BR8hkP0mQEsG29FM
        wmLbKrc0h9XPNytAuboDD+ttRYiO4rx1wmrnNSlqxFiuxB3IiWAx3g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T21:07:11Z"
  mac: ENC[AES256_GCM,data:0Ts+T0LVOcT3Z6+lKyuUEtKFMxzuQoCuI/1VRWcizbIU8EHrPQDQl/CHq30C9EQohDtTOM074AS/U4T5hJ9w9bmjc71mPly4OY+Q7lrUbzMpgtarkHxi+1roEebohXfSxAKAkB9nw6y+4KaFVPwMPiABcI9OCvMXG6PV3uW4uts=,iv:zxnZbBj4t2P5xOxYPp0FFKOeXAht7FCb988AFI9fTfg=,tag:y/qwAci4vFTAxnHVUgEuNA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
