# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:MG8n/2PAQC+MbTmFzDXei9c+NtMntJai1nCTm9tO3FyNuGeFdrmniQ==,iv:WrlVDnQtWg3OLhdxIt1TrNBZTklOs1aLEmhiVHFBEGE=,tag:Ec+GXMd7ylSBfele9dVq0w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qwj9jj75armxlhtv3mkh7h9fytldwu7ylkpy9ns807fxrr7e0fkq329d6e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBBTVNyOGNoTUNRQ1ZiL2ha
        eG41TS9HdkdwRStURnlrZTd4ak8xWHpQelVNCmRNN1RsZCsxMW1QUWRaSDZINitR
        ZURnTVZ2NzlQNjVNN3JlTmlkcG1iOTQKLS0tIEE3dEh3N2htNGoveXkxT0w4RE5G
        U1QzM0ZKZ1FkY090dlphMUhUNlZhQTAKhqjxDoLlg9TEKtcrq0WvFOLN7SeqknKe
        XgeDmbY5kLIV7UnV8l/kYBG3vVRAmEG+m2vk/F1kMEWnqWxkDe3wdA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T21:07:11Z"
  mac: ENC[AES256_GCM,data:NWCa7ATot3t+vhxUapeCfqsN9mamMfoVdU/RjFHJ7opO5Bwrcw0FpYSjArVjeJHCs42DcS0nFCuJcvGPuo8TsmRgBdLgsQ9d8qkvkoF7Ld6tZXXcL7Q0BzG/NhGbRqSeJITA08okTgkM5fJHjuCNXG99xpuaz2rtrNqegz8n1qQ=,iv:qe/h8xAckboJKDQejEoTnR+KDWiLhviQQ+PJOEffatw=,tag:7zIFNX4qdat07OoYEjukqg==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
