apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_ID: ENC[AES256_GCM,data:ENdH4C1brUI+QCt0+1dx+AmNcxVcT5pyO0SUBPnMsH6dv7iN,iv:ySsfXPgvIyaX2xq1U0/L4Wi01U1N/5UpS9PFom4nD8M=,tag:e7ysaRc8U5xH+bGIf53/OQ==,type:str]
  credentials.json: ENC[AES256_GCM,data:04sPniE2QQjLPEoqzMtTIYLuC7bUAUjbhKtppWLqGATT4JD/fY1rOr/QMlffl9XjUittOExbdricK9mRoFpDFSCqwKA9Tvlbrb28SnehvfkhFUY3fzMeZmeZ48WZNDP7pkgCn1Vx4op5oBfpt9VwfSjeZ3btoiRVNPmb8pLPPnc3RkpEU2lK9OBoGZn1O/qMPuRhEShxErWFU3ol6pHtDkzSJ4SSlG2ptSaFH7sBLg==,iv:xNNGJWYqxahDeQJmZsBpQruXy1b8Jl5iXRjCaqdW+yM=,tag:kmtJr4t86fD1WopSpt81Vw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1qwj9jj75armxlhtv3mkh7h9fytldwu7ylkpy9ns807fxrr7e0fkq329d6e
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTM3Jmc2k3SWVVZU01TXRP
        Nm8vdEJLb29zWG1FZnFaWkdONjJmUFZmUUhFCnNYQ0N5V0MxdVByZTZPajU0WkVj
        d3FPZXVyUVE4a2xuRzA1UFlJeWF1ekEKLS0tIHJ4aHNiU0pIb3dGZEE0azI1U0h2
        NjlJa0RqcHFKc3ZvOTBmb2R5NVI3WTgK8WbWzgN2rFwkKhwjz05de3KK/l62b7fU
        64dc5ip1utYniPoDxIn4WjaELnoQ3R+LVS1NExV9Vry+GD1tNXcR/Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-09T21:07:11Z"
  mac: ENC[AES256_GCM,data:AzU67Ogeny45KCA6Gr6LXliYN7etE7FSZaNEK+RKOXc9qcWjg1HN0PSC6lzXDEn2HTQBIryqHahMAm+JTUCO/t1WBXeD1Bz94oOGUUdqCjdT3dmGZUs2qtosdaRHc0RyWQE7nIiRSFB/ZYborShjpypGuHZh1TDezo5bwaLYAPQ=,iv:yBePd1U3FRhSCca6tDvCqqqQn5tpAfbDHejc/W9DyUw=,tag:GJ8pszcEWIgPA+EahhLjvw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
